#!/bin/bash

if [ -z "$1" ]; then
    echo "Uso: check-ssh ips.txt [usuario]";
else
    PORT=22
    TIMEOUT=2

    USER=root
    if [ -n "$2" ]; then
        USER="$2"
    fi

    while IFS= read -r SERVER; do
        if [ -n "$SERVER" ]; then
            if ssh -n -q -o BatchMode=yes -o StrictHostKeyChecking=no -o ConnectTimeout=$TIMEOUT "ssh://$USER@$SERVER:$PORT" "exit 0"; then
               echo "SSH a $SERVER -> OK"
            else
               echo "SSH a $SERVER -> ERROR"
            fi
        fi
    done < "$1"
fi
