#!/bin/bash

if [ -z "$1" ]; then
    echo "Uso: check-ssh ips.txt";
else
    port=22
    connect_timeout=2

    while IFS= read -r server; do
        ssh -n -q -o BatchMode=yes  -o StrictHostKeyChecking=no -o ConnectTimeout=$connect_timeout "ssh://root@$server:$port" "exit 0"
        if [ $? == 0 ];then
           echo "SSH a $server -> OK"
        else
           echo "SSH a $server -> ERROR"
        fi
    done < "$1"
fi
