#!/bin/bash

PORT=22
TIMEOUT=2

USER=root
if [ -n "$1" ]; then
    USER="$1"
fi

TOTAL=0;
OK=0;

IP="172.20.227."

for N in $(seq 1 240);
do
    SERVER=$IP$N;

        ((TOTAL += 1))

        if ssh -n -q -o BatchMode=yes -o StrictHostKeyChecking=no -o ConnectTimeout=$TIMEOUT "ssh://$USER@$SERVER:$PORT" "exit 0"; then
           echo "SSH a $SERVER -> OK"
           ((OK += 1))
        else
           echo "SSH a $SERVER -> ERROR"
        fi
done

echo ""
echo "Ok: $OK"
echo "Total: $TOTAL"
