#!/bin/bash

if [ -z "$1" ]; then
    echo "Uso: check-ssh ips.txt [usuario]";
else
    port=22
    connect_timeout=2

    USUARIO=root
    if [ -n "$2" ]; then
        USUARIO="$2"
    fi

    while IFS= read -r server; do
        ssh -n -q -o BatchMode=yes  -o StrictHostKeyChecking=no -o ConnectTimeout=$connect_timeout "ssh://$USUARIO@$server:$port" "exit 0"
        if [ $? == 0 ];then
           echo "SSH a $server -> OK"
        else
           echo "SSH a $server -> ERROR"
        fi
    done < "$1"
fi
